# -*- coding: utf-8 -*-
"""sum_of_n_natural_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oKyjQLTQZ-5PIt9s-gPsvmOGHpCj2-A
"""

#Sum of n natural numbers using an efficient function which takes O(1) constant time
def sum_of_num(n):
  return int(n*(n+1)/2)
num=int(input("Enter a number = "))
print(sum_of_num(num))